### ISSUE TITLE
Help - rotation and scaling problem 

### ISSUE THREAD

**Issue by jboteros** [keske/react-native-easy-gestures#27]
Hi how are you, I have problems with the rotation and the scale.

Use the component in the following ways and I can not get it to work.

`  <Gestures
          draggable={true}
          scalable={true}
          rotatable={true}
          onRelease={(event, styles) => {
            console.log(styles);
          }}
        >
          <Image
            source={Images.logoHeaderOrux}
            style={{
              width: 200,
              height: 200,
              resizeMode: "contain"
            }}
          />
        </Gestures>`

and 

`  <Gestures
          draggable={{
            x: true,
            y: true
          }}
          scalable={{
            min: 0.1,
            max: 200
          }}
          rotatable={true}
          onRelease={(event, styles) => {
            console.log(styles);
          }}
        >
          <Image
            source={Images.facebook_icon}
            style={{
              width: 200,
              height: 200,
              resizeMode: "contain"
            }}
          />
        </Gestures>`

Thanks

**Comment by keske** [comment]
Hello.

I've tried your examples and both are ok.

Try this code:

```javascript
<Gestures
  draggable={true}
  scalable={true}
  rotatable={true}
  onRelease={(event, styles) => {
    console.log(styles);
  }}
>
  <Image
    source={Images.logoHeaderOrux}
    style={{ width: 200, height: 200, resizeMode: 'contain' }}
  />
</Gestures>
```

```javascript
<Gestures
  draggable={{ x: true, y: true }}
  scalable={{ min: 0.1, max: 200 }}
  rotatable={true}
  onRelease={(event, styles) => { console.log(styles); }}
>
  <Image
    source={Images.facebook_icon}
    style={{ width: 200, height: 200, resizeMode: "contain" }}
  />
</Gestures>
````
