### ISSUE TITLE
Starting positions

### ISSUE THREAD

**Issue by radaalinmihai** [keske/react-native-easy-gestures#45]
Is there a way that I can set the starting styles on start? For example, I unmount the component but then I mount it again. The gestures component takes as starting values 0. How can I change this so that it begins from where it was before it was unmounted?

**Comment by ManigandanRaamanathan** [comment]
@radaalinmihai @keske any update on this? how can we set the default position to center?

**Comment by ManigandanRaamanathan** [comment]
@radaalinmihai @keske found the solution already. Just pass top and left keys in the style props directly like below:-
```
    style={{
        left: wp(34),
        top: hp(40)
    }}
```

**Comment by radaalinmihai** [comment]
if this is the fix then I shall close this issue
